language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/juliareleases -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'versioninfo(); Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("FinancialMarkets"))`); Pkg.pin("FinancialMarkets"); Pkg.resolve()'
  - julia -e 'using FinancialMarkets; @assert isdefined(:FinancialMarkets); @assert typeof(FinancialMarkets) === Module'
  - julia -e 'Pkg.test("FinancialMarkets", coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("FinancialMarkets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
